Pin pytest version to 7.3
pytest 7.4.0 breaks the possibility to add custom options to pytest.
Tests are failing with:

```
ERROR: usage: test_runner.py [options] [file_or_dir] [file_or_dir] [...]

test_runner.py: error: unrecognized arguments: --tests-log-file=...log --output-dir=.../eu-north-1 --key-name=... --key-path=...
```

Signed-off-by: Enrico Usai <usai@amazon.com>