Integ Tests: Add missing region fixture to update test
It was failing with:
botocore.exceptions.NoRegionError: You must specify a region.

Signed-off-by: Enrico Usai <usai@amazon.com>