Upgrade NCCL benchmark version to 2.10.0
The upgrade fixes compilation error on alinux2.
The 2.0.0 was wrongly introduced with:
https://github.com/aws/aws-parallelcluster/commit/00371121c9b3b1c018992e4c9675f043cdd234b7

```
Compiling  common.cu                           > ../build/common.o
Linking  ../build/all_reduce.o               > ../build/all_reduce_perf
/usr/bin/ld: cannot find -lmpi
collect2: error: ld returned 1 exit status
make[1]: *** [../build/all_reduce_perf] Error 1
make[1]: Leaving directory `/shared/openmpi/nccl-tests-2.0.0/src'
make: *** [src.build] Error 2
```

## Tests
* Manual compilation with both openmpi and intelmpi

Signed-off-by: Enrico Usai <usai@amazon.com>